# Generated by Django 4.1.7 on 2023-07-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('release_date', models.DateTimeField(auto_now=True)),
                ('reference_source', models.CharField(default='null', max_length=200, null=True)),
                ('author', models.CharField(default='null', max_length=200, null=True)),
                ('image', models.ImageField(default='null', null=True, upload_to='')),
            ],
        ),
    ]
