# Generated by Django 4.2 on 2023-08-29 10:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('邮箱', models.EmailField(max_length=254)),
                ('主题', models.CharField(max_length=255)),
                ('内容', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='书库',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('作者', models.CharField(blank=True, max_length=200, null=True)),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('文档', models.FileField(upload_to='pdf/shuku/')),
                ('作者简介', ckeditor.fields.RichTextField()),
                ('内容简介', ckeditor.fields.RichTextField()),
                ('出版日期', models.DateField(blank=True, default='暂无', null=True)),
                ('图片', sorl.thumbnail.fields.ImageField(default='null', null=True, upload_to='images/shuku/')),
                ('序号', models.CharField(max_length=30)),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='书讯',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('内容简介', ckeditor.fields.RichTextField(blank=True, default='暂无内容简介', max_length=300, null=True)),
                ('作者简介', ckeditor.fields.RichTextField(blank=True, default='暂无作者简介', max_length=300, null=True)),
                ('目录', ckeditor.fields.RichTextField(blank=True, default='暂无', null=True)),
                ('前言', ckeditor.fields.RichTextField(blank=True, default='暂无', null=True)),
                ('ISBN', models.CharField(blank=True, default='暂无', max_length=30, null=True)),
                ('作者', models.CharField(blank=True, default='暂无', max_length=200, null=True)),
                ('出版社', models.CharField(blank=True, default='暂无', max_length=200, null=True)),
                ('出版年', models.DateField(blank=True, default='暂无', null=True)),
                ('定价', models.IntegerField(blank=True, null=True)),
                ('页数', models.IntegerField(blank=True, null=True)),
                ('装帧', models.CharField(blank=True, default='暂无', max_length=20, null=True)),
                ('图片', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/shuxun/')),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='书评',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('书籍作者', models.CharField(blank=True, max_length=200, null=True)),
                ('书籍出版日期', models.DateField(blank=True, null=True)),
                ('书评内容', ckeditor.fields.RichTextField()),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('书评作者', models.CharField(blank=True, max_length=200, null=True)),
                ('图片', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/shuping/')),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='古籍',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('作者', models.CharField(blank=True, max_length=200, null=True)),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('文档', models.FileField(upload_to='pdf/guji/')),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='提问_问答',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('通过', models.BooleanField(default=False)),
                ('发布时间', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='文史',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('内容', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('作者', models.CharField(blank=True, max_length=200, null=True)),
                ('图片', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/wenshi/')),
                ('资源', models.CharField(blank=True, max_length=200, null=True)),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='文艺',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('内容', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('作者', models.CharField(blank=True, max_length=200, null=True)),
                ('图片', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/wenyi/')),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='经训',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('图片', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/jingxun/')),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='观点',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('内容', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('作者', models.CharField(blank=True, max_length=200, null=True)),
                ('图片', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/guandian/')),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='视频',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('视频文件', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('发布状态', models.BooleanField(default=False)),
                ('更新时间', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='论文',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('作者', models.CharField(blank=True, max_length=200, null=True)),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('文档', models.FileField(default='null', null=True, upload_to='pdf/lunwen/')),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='译林',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('译文作者', models.CharField(blank=True, max_length=100, null=True)),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('原文标题', models.CharField(max_length=150)),
                ('译文内容', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('原文作者', models.CharField(blank=True, max_length=100, null=True)),
                ('原文出版日期', models.DateField(blank=True, null=True)),
                ('图片', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/yiling/')),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='通讯',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('内容', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('发布状态', models.BooleanField(default=False)),
                ('资源', models.CharField(blank=True, default='无资源信息', max_length=200, null=True)),
                ('作者', models.CharField(blank=True, default='无作者信息', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='问答',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('答案', ckeditor.fields.RichTextField(blank=True)),
                ('序号', models.CharField(blank=True, max_length=4)),
                ('参考问答', models.BooleanField(default=False)),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('发布状态', models.BooleanField(default=False)),
                ('参考问答项目', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.问答')),
            ],
        ),
        migrations.CreateModel(
            name='评论_问答',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.CharField(default='审查中', max_length=100)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('问答', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.问答')),
            ],
        ),
        migrations.CreateModel(
            name='评论_视频',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.CharField(default='审查中', max_length=100)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('视频', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.视频')),
            ],
        ),
        migrations.CreateModel(
            name='评论_观点',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.CharField(default='审查中', max_length=100)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('观点', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.观点')),
            ],
        ),
        migrations.CreateModel(
            name='评论_文艺',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.CharField(default='审查中', max_length=100)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('文艺', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.文艺')),
            ],
        ),
        migrations.CreateModel(
            name='评论_文史',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.CharField(default='审查中', max_length=100)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('文史', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.文史')),
            ],
        ),
        migrations.CreateModel(
            name='评论_书评',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.CharField(default='审查中', max_length=100)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('书评', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.书评')),
            ],
        ),
        migrations.CreateModel(
            name='章节_经训',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('章节', models.CharField(max_length=150)),
                ('内容', ckeditor.fields.RichTextField()),
                ('经训', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.经训')),
            ],
        ),
    ]
