# Generated by Django 4.1.7 on 2023-08-05 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='书库',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('作者', models.CharField(blank=True, max_length=200, null=True)),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('文档', models.FileField(upload_to='pdf/shuku/')),
                ('简介', models.TextField()),
                ('图片', models.ImageField(default='null', null=True, upload_to='images/shuku/')),
                ('序号', models.IntegerField()),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='书讯',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('简介', models.TextField()),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('发布状态', models.BooleanField(default=False)),
                ('序号', models.IntegerField(blank=True, null=True)),
                ('作者', models.CharField(blank=True, max_length=200, null=True)),
                ('图片', models.ImageField(blank=True, null=True, upload_to='images/shuxun/')),
            ],
        ),
        migrations.CreateModel(
            name='书评',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('书籍作者', models.CharField(blank=True, max_length=200, null=True)),
                ('书籍出版日期', models.DateField(blank=True, null=True)),
                ('书评内容', models.TextField()),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('书评作者', models.CharField(blank=True, max_length=200, null=True)),
                ('图片', models.ImageField(default='null', null=True, upload_to='images/shuping/')),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='古籍',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('作者', models.CharField(blank=True, max_length=200, null=True)),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('文档', models.FileField(upload_to='pdf/guji/')),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='文摘',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('内容', models.TextField()),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('作者', models.CharField(blank=True, max_length=200, null=True)),
                ('图片', models.ImageField(default='null', null=True, upload_to='images/wenzhai/')),
                ('资源', models.CharField(blank=True, max_length=200, null=True)),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='文艺',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('内容', models.TextField()),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('作者', models.CharField(default='null', max_length=200, null=True)),
                ('图片', models.ImageField(default='null', null=True, upload_to='')),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='经训',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('章节', models.CharField(max_length=150)),
                ('原文作者', models.CharField(max_length=150)),
                ('译文作者', models.CharField(max_length=150)),
                ('标题', models.CharField(max_length=150)),
                ('内容', models.TextField()),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='观点',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('内容', models.TextField()),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('作者', models.CharField(default='null', max_length=200, null=True)),
                ('图片', models.ImageField(default='null', null=True, upload_to='')),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='论文',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('作者', models.CharField(blank=True, max_length=200, null=True)),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('文档', models.FileField(default='null', null=True, upload_to='pdf/lunwen/')),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='译林',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('译文作者', models.CharField(blank=True, max_length=100, null=True)),
                ('更新时间', models.DateField(auto_now=True)),
                ('原文标题', models.CharField(max_length=150)),
                ('原文内容', models.TextField()),
                ('原文作者', models.CharField(blank=True, max_length=100, null=True)),
                ('原文发布时间', models.DateTimeField(auto_now=True)),
                ('图片', models.ImageField(blank=True, null=True, upload_to='images/yiling/')),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='通讯',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('内容', models.TextField()),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('发布状态', models.BooleanField(default=False)),
                ('资源', models.CharField(blank=True, max_length=200, null=True)),
                ('作者', models.CharField(blank=True, max_length=200, null=True)),
                ('图片', models.ImageField(blank=True, null=True, upload_to='images/tongxun/')),
            ],
        ),
        migrations.CreateModel(
            name='问答',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('答案', models.TextField()),
                ('序号', models.IntegerField()),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('发布状态', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='评论_问答',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.BooleanField(default=False)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('问答', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.问答')),
            ],
        ),
        migrations.CreateModel(
            name='评论_观点',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.BooleanField(default=False)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('观点', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.观点')),
            ],
        ),
        migrations.CreateModel(
            name='评论_文艺',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.BooleanField(default=False)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('文艺', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.文艺')),
            ],
        ),
        migrations.CreateModel(
            name='评论_文摘',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.BooleanField(default=False)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('文摘', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.文摘')),
            ],
        ),
        migrations.CreateModel(
            name='评论_书评',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.BooleanField(default=False)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('书评', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.书评')),
            ],
        ),
    ]
