# Generated by Django 4.1.7 on 2023-07-06 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='通讯',
        ),
    ]
