# Generated by Django 4.2 on 2023-08-21 14:26

from django.db import migrations, models
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='书库',
            name='图片',
            field=optimized_image.fields.OptimizedImageField(default='null', null=True, upload_to='images/shuku/'),
        ),
        migrations.AlterField(
            model_name='书讯',
            name='作者',
            field=models.CharField(blank=True, default='无作者信息', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='书讯',
            name='图片',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='images/shuxun/'),
        ),
        migrations.AlterField(
            model_name='书评',
            name='图片',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='images/shuping/'),
        ),
        migrations.AlterField(
            model_name='文摘',
            name='图片',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='images/wenzhai/'),
        ),
        migrations.AlterField(
            model_name='文艺',
            name='图片',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='images/wenyi/'),
        ),
        migrations.AlterField(
            model_name='经训',
            name='图片',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='images/jingxun/'),
        ),
        migrations.AlterField(
            model_name='观点',
            name='图片',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='images/guandian/'),
        ),
        migrations.AlterField(
            model_name='译林',
            name='图片',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='images/yiling/'),
        ),
        migrations.AlterField(
            model_name='通讯',
            name='作者',
            field=models.CharField(blank=True, default='无作者信息', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='通讯',
            name='图片',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='images/tongxun/'),
        ),
        migrations.AlterField(
            model_name='通讯',
            name='资源',
            field=models.CharField(blank=True, default='无资源信息', max_length=200, null=True),
        ),
    ]
