# Generated by Django 4.1.7 on 2023-08-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='书评',
            name='图片',
            field=models.ImageField(blank=True, null=True, upload_to='images/shuping/'),
        ),
    ]
