# Generated by Django 4.1.7 on 2023-07-06 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_news_通讯'),
    ]

    operations = [
        migrations.RenameField(
            model_name='通讯',
            old_name='author',
            new_name='作者',
        ),
        migrations.RenameField(
            model_name='通讯',
            old_name='content',
            new_name='内容',
        ),
        migrations.RenameField(
            model_name='通讯',
            old_name='release_date',
            new_name='发布日期',
        ),
        migrations.RenameField(
            model_name='通讯',
            old_name='image',
            new_name='图片',
        ),
        migrations.RenameField(
            model_name='通讯',
            old_name='title',
            new_name='标题',
        ),
        migrations.RenameField(
            model_name='通讯',
            old_name='reference_source',
            new_name='资源',
        ),
    ]
