# Generated by Django 4.1.7 on 2023-08-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_书评_图片'),
    ]

    operations = [
        migrations.RenameField(
            model_name='译林',
            old_name='原文内容',
            new_name='译文内容',
        ),
    ]
