# Generated by Django 4.2 on 2023-08-22 04:21

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_书库_图片_alter_书讯_作者_alter_书讯_图片_alter_书评_图片_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='书库',
            name='图片',
            field=sorl.thumbnail.fields.ImageField(default='null', null=True, upload_to='images/shuku/'),
        ),
        migrations.AlterField(
            model_name='书讯',
            name='图片',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/shuxun/'),
        ),
        migrations.AlterField(
            model_name='书评',
            name='图片',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/shuping/'),
        ),
        migrations.AlterField(
            model_name='文摘',
            name='图片',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/wenzhai/'),
        ),
        migrations.AlterField(
            model_name='文艺',
            name='图片',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/wenyi/'),
        ),
        migrations.AlterField(
            model_name='经训',
            name='图片',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/jingxun/'),
        ),
        migrations.AlterField(
            model_name='观点',
            name='图片',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/guandian/'),
        ),
        migrations.AlterField(
            model_name='译林',
            name='图片',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/yiling/'),
        ),
        migrations.AlterField(
            model_name='通讯',
            name='图片',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/tongxun/'),
        ),
    ]
