# Generated by Django 4.1.7 on 2023-08-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_原文内容_译林_译文内容'),
    ]

    operations = [
        migrations.RenameField(
            model_name='译林',
            old_name='原文发布时间',
            new_name='原文发布日期',
        ),
    ]
