# Generated by Django 4.1.7 on 2023-07-06 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_author_通讯_作者_rename_content_通讯_内容_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='书库',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('作者', models.CharField(default='null', max_length=200, null=True)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('文档', models.FileField(upload_to='')),
                ('简介', models.TextField()),
                ('图片', models.ImageField(upload_to='')),
                ('序号', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='书讯',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('简介', models.TextField()),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('序号', models.IntegerField(default='null', null=True)),
                ('作者', models.CharField(default='null', max_length=200, null=True)),
                ('图片', models.ImageField(default='null', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='书评',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('书籍标题', models.CharField(max_length=150)),
                ('书籍作者', models.CharField(default='null', max_length=200, null=True)),
                ('书籍发布日期', models.DateField(auto_now=True)),
                ('书评内容', models.TextField()),
                ('书评发布时间', models.DateTimeField(auto_now=True)),
                ('书评作者', models.CharField(default='null', max_length=200, null=True)),
                ('图片', models.ImageField(default='null', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='古籍',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('作者', models.CharField(default='null', max_length=200, null=True)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('文档', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='文摘',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('内容', models.TextField()),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('作者', models.CharField(default='null', max_length=200, null=True)),
                ('图片', models.ImageField(default='null', null=True, upload_to='')),
                ('资源', models.CharField(default='null', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='文艺',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('内容', models.TextField()),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('作者', models.CharField(default='null', max_length=200, null=True)),
                ('图片', models.ImageField(default='null', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='经训',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('章节', models.CharField(max_length=150)),
                ('原文作者', models.CharField(max_length=150)),
                ('译文作者', models.CharField(max_length=150)),
                ('标题', models.CharField(max_length=150)),
                ('内容', models.TextField()),
                ('发布时间', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='观点',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('内容', models.TextField()),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('作者', models.CharField(default='null', max_length=200, null=True)),
                ('图片', models.ImageField(default='null', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='论文',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('作者', models.CharField(default='null', max_length=200, null=True)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('文档', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='译林',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('译文标题', models.CharField(max_length=150)),
                ('译文作者', models.CharField(default='null', max_length=200, null=True)),
                ('译文发布日期', models.DateField(auto_now=True)),
                ('原文标题', models.CharField(max_length=150)),
                ('原文内容', models.TextField()),
                ('原文作者', models.CharField(default='null', max_length=200, null=True)),
                ('原文发布时间', models.DateTimeField(auto_now=True)),
                ('图片', models.ImageField(default='null', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='问答',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('问题', models.CharField(max_length=150)),
                ('回答', models.TextField()),
                ('序号', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='通讯',
            old_name='发布日期',
            new_name='发布时间',
        ),
        migrations.CreateModel(
            name='评论_问答',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.BooleanField(default=False)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('问答', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.问答')),
            ],
        ),
        migrations.CreateModel(
            name='评论_观点',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.BooleanField(default=False)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('观点', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.观点')),
            ],
        ),
        migrations.CreateModel(
            name='评论_文艺',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.BooleanField(default=False)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('文艺', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.文艺')),
            ],
        ),
        migrations.CreateModel(
            name='评论_文摘',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.BooleanField(default=False)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('文摘', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.文摘')),
            ],
        ),
        migrations.CreateModel(
            name='评论_书评',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.BooleanField(default=False)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('书评', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.书评')),
            ],
        ),
    ]
