# Generated by Django 4.1.7 on 2023-08-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_书库_书讯_书评_古籍_文摘_文艺_经训_观点_论文_译林_问答_rename_发布日期_通讯_发布时间_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='通讯',
            old_name='发布时间',
            new_name='更新时间',
        ),
        migrations.RenameField(
            model_name='问答',
            old_name='回答',
            new_name='答案',
        ),
        migrations.AddField(
            model_name='通讯',
            name='发布状态',
            field=models.BooleanField(default=False),
        ),
    ]
