# Generated by Django 4.2 on 2023-08-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='主题',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='邮箱',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='内容',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
