# Generated by Django 4.1.7 on 2023-08-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_原文发布时间_译林_原文发布日期'),
    ]

    operations = [
        migrations.AlterField(
            model_name='译林',
            name='原文发布日期',
            field=models.DateField(auto_now=True),
        ),
    ]
