# Generated by Django 4.1.7 on 2023-08-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_译林_原文发布日期'),
    ]

    operations = [
        migrations.RenameField(
            model_name='译林',
            old_name='原文发布日期',
            new_name='原文出版日期',
        ),
    ]
