# Generated by Django 4.1.7 on 2023-08-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_原文发布日期_译林_原文出版日期'),
    ]

    operations = [
        migrations.AlterField(
            model_name='译林',
            name='原文出版日期',
            field=models.DateField(blank=True, null=True),
        ),
    ]
