# Generated by Django 4.1.7 on 2023-08-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_通讯_图片'),
    ]

    operations = [
        migrations.RenameField(
            model_name='书讯',
            old_name='发布时间',
            new_name='更新时间',
        ),
        migrations.AddField(
            model_name='书讯',
            name='发布状态',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='通讯',
            name='作者',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='通讯',
            name='图片',
            field=models.ImageField(blank=True, null=True, upload_to='images/tongxun/'),
        ),
        migrations.AlterField(
            model_name='通讯',
            name='资源',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
