# Generated by Django 4.2 on 2023-08-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_通讯_图片'),
    ]

    operations = [
        migrations.AlterField(
            model_name='通讯',
            name='作者',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='通讯',
            name='图片',
            field=models.ImageField(blank=True, null=True, upload_to='images/tongxun/'),
        ),
        migrations.AlterField(
            model_name='通讯',
            name='资源',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
