# Generated by Django 4.1.7 on 2023-08-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_通讯_作者_alter_通讯_图片_alter_通讯_资源'),
        ('home', '0007_rename_发布时间_书讯_更新时间_书讯_发布状态_alter_通讯_作者_alter_通讯_图片_and_more'),
    ]

    operations = [
    ]
