# Generated by Django 4.1.7 on 2023-08-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_译林_原文出版日期'),
    ]

    operations = [
        migrations.AlterField(
            model_name='译林',
            name='更新时间',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
