# Generated by Django 4.1.7 on 2023-08-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_文摘_图片_alter_评论_书评_通过'),
    ]

    operations = [
        migrations.AlterField(
            model_name='观点',
            name='作者',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='观点',
            name='图片',
            field=models.ImageField(blank=True, null=True, upload_to='images/guandian/'),
        ),
        migrations.AlterField(
            model_name='评论_书评',
            name='通过',
            field=models.CharField(default='审查中', max_length=100),
        ),
    ]
