# Generated by Django 4.1.7 on 2023-08-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_观点_作者_alter_观点_图片_alter_评论_书评_通过'),
    ]

    operations = [
        migrations.AlterField(
            model_name='评论_观点',
            name='通过',
            field=models.CharField(default='审查中', max_length=100),
        ),
    ]
