# Generated by Django 4.2 on 2023-08-07 02:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_文摘_内容'),
    ]

    operations = [
        migrations.AlterField(
            model_name='译林',
            name='译文内容',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
