# Generated by Django 4.2 on 2023-08-07 02:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_译林_译文内容'),
    ]

    operations = [
        migrations.AlterField(
            model_name='文艺',
            name='内容',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='观点',
            name='内容',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='通讯',
            name='内容',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
