# Generated by Django 4.1.7 on 2023-08-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_文艺_作者_alter_文艺_图片_alter_评论_文艺_通过'),
    ]

    operations = [
        migrations.CreateModel(
            name='视频',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('视频类型', models.CharField(max_length=150)),
                ('视频链接', models.URLField()),
                ('视频档案', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('发布状态', models.BooleanField(default=False)),
                ('更新时间', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='评论_视频',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论', models.CharField(max_length=200)),
                ('通过', models.CharField(default='审查中', max_length=100)),
                ('发布时间', models.DateTimeField(auto_now=True)),
                ('视频', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.视频')),
            ],
        ),
    ]
