# Generated by Django 4.1.7 on 2023-08-08 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_文艺_内容_alter_观点_内容_alter_通讯_内容'),
        ('home', '0013_视频_评论_视频'),
    ]

    operations = [
    ]
