# Generated by Django 4.1.7 on 2023-08-08 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merge_20230808_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='视频',
            old_name='视频档案',
            new_name='视频文件',
        ),
    ]
