# Generated by Django 4.1.7 on 2023-08-08 00:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_视频档案_视频_视频文件'),
    ]

    operations = [
        migrations.AlterField(
            model_name='书讯',
            name='简介',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='书评',
            name='书评内容',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
