# Generated by Django 4.1.7 on 2023-08-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_书讯_简介_alter_书评_书评内容'),
    ]

    operations = [
        migrations.AlterField(
            model_name='视频',
            name='视频类型',
            field=models.CharField(choices=[('线上网址', '线上网址'), ('本地上载', '本地上载')], max_length=150),
        ),
    ]
