# Generated by Django 4.1.7 on 2023-08-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_视频_视频类型'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='视频',
            name='视频类型',
        ),
        migrations.RemoveField(
            model_name='视频',
            name='视频链接',
        ),
    ]
