# Generated by Django 4.1.7 on 2023-08-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_视频_视频类型_remove_视频_视频链接'),
    ]

    operations = [
        migrations.CreateModel(
            name='提问_问答',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=150)),
                ('通过', models.BooleanField(default=False)),
                ('发布时间', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='问答',
            name='参考问答',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='问答',
            name='参考问答项目',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.问答'),
        ),
        migrations.AlterField(
            model_name='问答',
            name='序号',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
