# Generated by Django 4.1.7 on 2023-08-08 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_提问_问答_问答_参考问答_问答_参考问答项目_alter_问答_序号'),
    ]

    operations = [
        migrations.AlterField(
            model_name='问答',
            name='参考问答项目',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.问答'),
        ),
    ]
