# Generated by Django 4.1.7 on 2023-08-09 04:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_问答_参考问答项目'),
    ]

    operations = [
        migrations.AlterField(
            model_name='评论_问答',
            name='通过',
            field=models.CharField(default='审查中', max_length=100),
        ),
        migrations.AlterField(
            model_name='问答',
            name='答案',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
