# Generated by Django 4.1.7 on 2023-08-09 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_评论_问答_通过_alter_问答_答案'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='经训',
            name='内容',
        ),
        migrations.RemoveField(
            model_name='经训',
            name='原文作者',
        ),
        migrations.RemoveField(
            model_name='经训',
            name='章节',
        ),
        migrations.RemoveField(
            model_name='经训',
            name='译文作者',
        ),
        migrations.AddField(
            model_name='经训',
            name='图片',
            field=models.ImageField(blank=True, null=True, upload_to='images/jingxun/'),
        ),
        migrations.CreateModel(
            name='章节_经训',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('章节', models.CharField(max_length=150)),
                ('内容', models.TextField()),
                ('经训', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.经训')),
            ],
        ),
    ]
